version: '3.8'

services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    environment:
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - JIRA_URL=${JIRA_URL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - ENABLED_TOOLS=confluence_search,confluence_get_page_children,confluence_get_comments,confluence_get_labels,confluence_get_page,confluence_add_comment,jira_get_issue,jira_search
    stdin_open: true
    tty: true
    restart: unless-stopped

  mcp-github:
    image: ghcr.io/github/github-mcp-server:latest
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    stdin_open: true
    tty: true
    restart: unless-stopped
  mcp-slack:
    image: mcp/slack
    environment:
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
      - SLACK_CHANNEL_IDS=${SLACK_CHANNEL_IDS}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    stdin_open: true
    tty: true
    restart: unless-stopped
